version: '3.7'
services:
    redis1:
        build:
            context: .
            dockerfile: Dockerfile-base
            args:
                PORT_CONFIG: 7001
                PORT_BUS_CONFIG: 8101
                IP: 173.17.0.2
        networks:
            app_net:
                ipv4_address: 173.17.0.2
        ports:
            - "7001:7001"
            - "8101:8101"
    redis2:
        build:
            context: .
            dockerfile: Dockerfile-base
            args:
                PORT_CONFIG: 7002
                PORT_BUS_CONFIG: 8102
                IP: 173.17.0.3
        networks:
            app_net:
                ipv4_address: 173.17.0.3
        ports:
            - "7002:7002"
            - "8102:8102"
    redis3:
        build:
            context: .
            dockerfile: Dockerfile-base
            args:
                PORT_CONFIG: 7003
                PORT_BUS_CONFIG: 8103
                IP: 173.17.0.4
        networks:
            app_net:
                ipv4_address: 173.17.0.4
        ports:
            - "7003:7003"
            - "8103:8103"
    redis-cluster:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        hostname: server
        depends_on:
            - redis1
            - redis2
            - redis3
        ports:
            - "7000:7000"
            - "17000:17000"
        networks:
            app_net:
                ipv4_address: 173.17.0.5
networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 173.17.0.0/16