version: '3.7'
services:
    redis1:
        build:
            context: .
            dockerfile: Dockerfile-base
            args:
                PORT_CONFIG: 7001
                PORT_BUS_CONFIG: 8101
        network_mode: "host"
        ports:
            - "7001:7001"
            - "8101:8101"
    redis2:
        build:
            context: .
            dockerfile: Dockerfile-base
            args:
                PORT_CONFIG: 7002
                PORT_BUS_CONFIG: 8102
        network_mode: "host"
        ports:
            - "7002:7002"
            - "8102:8102"
    redis3:
        build:
            context: .
            dockerfile: Dockerfile-base
            args:
                PORT_CONFIG: 7003
                PORT_BUS_CONFIG: 8103
        network_mode: "host"
        ports:
            - "7003:7003"
            - "8103:8103"
    redis-cluster:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        hostname: server
        depends_on:
            - redis1
            - redis2
            - redis3
        ports:
            - "7000:7000"
            - "17000:17000"
        network_mode: "host"